floor = 1
ceil = 2
doubles = false
last_exercise = "Planche"

[exercises]
Pullup = { type = "Reps", profiles = { normal = false } }
Pushup = { type = "Reps", profiles = { normal = false } }
Planche = { type = "Reps", profiles = { normal = true } }
Fischel = { type = "Reps", profiles = { normal = true } }
