[Pushup]
reps = 2848
amount = 77
max = 50

[Lean]
reps = 190
amount = 190
max = 1

[Abs]
reps = 207
amount = 14
max = 20

[Lever]
reps = 59
amount = 59
max = 1

[Pullup]
reps = 1246
amount = 52
max = 26

[Sally]
Time = 1392
amount = 7
max = 204

[Swing]
reps = 87
amount = 67
max = 9

[Planche]
reps = 34
amount = 34
max = 1

[Planche-Pushup]
reps = 34
amount = 5
max = 8

[Handstand]
reps = 1
amount = 1
max = 1

[Stretch]
reps = 1
amount = 1
max = 1
