[Pushup]
Reps = 2529
Amount = 67
Max = 50

[Lean]
Reps = 190
Amount = 190
Max = 1

[Abs]
Reps = 207
Amount = 14
Max = 20

[Lever]
Reps = 59
Amount = 59
Max = 1

[Pullup]
Reps = 1246
Amount = 52
Max = 26

[Sally]
Time = 1392
Amount = 7
Max = 204

[Swing]
Reps = 87
Amount = 67
Max = 9

[Planche]
Reps = 28
Amount = 28
Max = 1

[PlanchePushup]
Reps = 5
Amount = 1
Max = 5
