import { Theme } from "Theme.slint";
import { HorizontalBox } from "std-widgets.slint";

component StartButton inherits Rectangle {
    in-out property <bool> status;
    in-out property <int> time;

    callback button_pressed();

    height: 300px;
    width: self.height;
    background: status ? Theme.accent : Theme.negative_accent;
    border-radius: self.height/2;
    clip: true;
    
    Text {
        text: status ? "Start" : time + "s";
        font-size: 40px;
        font-family: "Inter";
    }

    TouchArea {
        width: parent.width;
        height: parent.height;
        clicked => { 
            root.button_pressed();
        }
    }
}

export component BasicButton {
    callback start_pressed(string, string);

    //Interval Inputs
    in-out property <int> initial_floor_value;
    in-out property <int> initial_ceil_value;

    //Start Button
    in-out property <bool> start_button_status: true;
    in-out property <int> passed_time: 0;

    in property <string> current_profile;


    HorizontalLayout {
        alignment: center;
        VerticalLayout {
            spacing: 20px;
            alignment: center;
            HorizontalLayout {
                alignment: center;
                start_button := StartButton {
                    
                    time: passed_time;
                    status: start_button_status;
                    button_pressed => {
                        root.start_pressed(floor_input.text, ceil_input.text);
                    }
                }
            }

            HorizontalBox {
                Text {
                    //width: 150px;
                    text: "Current Profile: " + root.current_profile;
                    wrap: word-wrap;
                    horizontal-alignment: center;
                    vertical-alignment: center;
                    font-size: 18px;
                    font-family: "Inter";
                    color: Theme.border_color;
                }
            }
            
            HorizontalLayout {
                alignment: center;
                spacing: 10px;
                Rectangle {
                    width: 150px;
                    height: 40px;
                    background: Theme.container1;
                    border-radius: 10px;
                    border-width: 1px;
                    border-color: Theme.border_color;
                    
                    floor_input := TextInput {
                        color: Theme.font_color_light;
                        font-size: 20px;
                        input-type: number;
                        text: initial_floor_value;
                        horizontal-alignment: center;
                        vertical-alignment: center;
                        font-family: "Inter";

                        accepted => {
                            root.start_pressed(floor_input.text, ceil_input.text);
                        }
                    }
                }
                Rectangle {
                    width: 150px;
                    height: 40px;
                    background: Theme.container1;
                    border-radius: 10px;
                    border-width: 1px;
                    border-color: Theme.border_color;
                    
                    ceil_input := TextInput {
                        color: Theme.font_color_light;
                        font-size: 20px;
                        input-type: number;
                        text: initial_ceil_value;
                        horizontal-alignment: center;
                        vertical-alignment: center;
                        font-family: "Inter";

                        accepted => {
                            root.start_pressed(floor_input.text, ceil_input.text);
                        }
                    }
                }            
            }
        }
    }
}
