export component RepInput inherits Rectangle {
    callback save_reps(string);

    in property <string> exercise;

    VerticalLayout {
        alignment: center;
        spacing: 5px;
        HorizontalLayout {
            alignment: center;
            Text {
                text: exercise + "s";
                font-size: 40px;
                color: #026F8F;
            }
        }
        HorizontalLayout {
            alignment: center;
            padding: 10px;
            Text {
                text: "Enter amount of completed reps below";
                font-size: 15px;
            }
        }
        HorizontalLayout {
            alignment: center;
            Rectangle {
                width: 150px;
                height: 40px;
                background: #41667188;
                border-radius: 10px;
                border-width: 1px;
                border-color: Colors.black;
        
                reps := TextInput {
                    color: Colors.white;
                    font-size: 20px;
                    text: "0";
                    input-type: number;
                    horizontal-alignment: center;
                    vertical-alignment: center;

                    accepted => {
                        root.save_reps(reps.text);
                        reps.text = "0";
                    }
                }
            }
        }
        HorizontalLayout {
            alignment: center;
            Rectangle {
                width: 80px;
                height: 40px;
                background: #026F8F;
                border-radius: 10px;
                border-width: 1px;
                border-color: Colors.black;
    
                Text {
                    text: "Save";
                    font-size: 20px;
                }

                TouchArea {
                    width: parent.width;
                    height: parent.height;
                    clicked => { 
                        root.save_reps(reps.text);
                        reps.text = "0";
                    }
                }
            }
        }
    }
}
