import { HorizontalBox, VerticalBox, TabWidget, ComboBox, Switch, ListView } from "std-widgets.slint";

//Structs
export struct Exercise {
    name: string,
    activation_status: bool,
}

export component Settings {
    callback changed_general(bool);
    callback changed_activation(string);
    callback add_exercise(string, string);
    callback remove_exercise(string);
    callback add_reps(string, string);

    in property <bool> setting_general_doubles;
    in-out property <[Exercise]> exercises;
    in-out property <[string]> exercise_names;
    in-out property <bool> add_exercise_vis: false;
    in-out property <bool> remove_exercise_vis: false;
    in-out property <bool> add_reps_vis: false;
    in-out property <[string]> profile_names;

    width: 600px;
    height: 400px;

    Rectangle {
        y: -140px;
        width: 200px;
        height: 80px;
        background: add_reps_vis ? #B71C1C : #026F8F;
        border-radius: 5px;
        border-width: 2px;
        border-color: #000000;
        
        Text {
            text: "Add Reps";
            font-size: 30px;
        }

        TouchArea {
            clicked => {
                add_reps_vis = !add_reps_vis;
                add_rep_box.current-index = 0;
                add_reps_input.text = "Reps";
            }
        }
    }

    Rectangle {
        visible: add_reps_vis;
        width: 400px;
        height: 300px;
        border-color: #6b6868;
        border-width: 1.5px;
        border-radius: 2px;

        VerticalBox {
            alignment: center;
            HorizontalBox {
                alignment: center;
                add_rep_box := ComboBox {
                    width: 200px;
                    model: exercise_names;
                }
            }

            HorizontalBox {
                alignment: center;
                add_reps_input := TextInput {
                    text: "Reps";
                    font-size: 20px;
                    width: 200px;
                    horizontal-alignment: center;
    
                    accepted => {
                        add_reps(add_rep_box.current-value, add_reps_input.text);
                        add_reps_vis = !add_reps_vis;
                    }
                }
                
            }

            HorizontalBox {
                alignment: center;

                Rectangle {
                    width: 80px;
                    height: 40px;
                    background: #026F8F;
                    border-radius: 3px;
                    border-width: 1px;
                    border-color: #000000;
                    
                    Text {
                        text: "Add";
                        font-size: 20px;
                    }
        
                    TouchArea {
                        clicked => {
                            add_reps(add_rep_box.current-value, add_reps_input.text);
                            add_reps_vis = !add_reps_vis;
                        }
                    }
                }
            }
        }
    }

    Rectangle {
        visible: !add_reps_vis;
        border-radius: 2px;
        border-width: 1px;
        border-color: #6b6868;
        TabWidget {
            //TODO einzelne Tabs in files
            Tab {
                title: "General";
                Rectangle {
                    VerticalBox {
                        alignment: start;
                        Rectangle {
                            width: 205px;
                            height: 40px;
                            border-width: 5px;
                            padding: 10px;
                            
                            Rectangle {
                                width: 200px; 
                                height: 35px;
                                border-width: 1.5px;
                                border-radius: 2px;
                                border-color: #6b6868;
                                HorizontalBox {
                                    Text {
                                        text: "Doubles";
                                        font-size: 16px;
                                    }
                
                                    doubles := Switch {
                                        checked: setting_general_doubles;
                                        toggled => {
                                            changed_general(doubles.checked);
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }

                                                
            Tab {
                title: "Exercises";
                VerticalBox {
                    HorizontalBox {
                        alignment: center;
                        spacing: 15px;
                        Rectangle {
                            height: 30px;
                            width: 30px;
                            background: add_exercise_vis ? #B71C1C : #026F8F;
                            border-radius: 2px;
                            
                            Image {
                                width: parent.width*0.6;
                                height: parent.height*0.6;
                                source: @image-url("resources/icon_plus.png");
                            }

                            TouchArea {
                                enabled: !remove_exercise_vis;
                                clicked => {
                                    add_exercise_vis = !add_exercise_vis;
                                }
                            }
                        }

                        Rectangle {
                            height: 30px;
                            width: 30px;
                            background: remove_exercise_vis ? #B71C1C : #026F8F;
                            border-radius: 2px;

                            Image {
                                width: parent.width*0.6;
                                height: parent.height*0.5;
                                source: @image-url("resources/icon_minus.png");
                            }

                            TouchArea {
                                enabled: !add_exercise_vis;
                                clicked => {
                                    remove_exercise_vis = !remove_exercise_vis;
                                }
                            }
                        }
                    }
                                        
                    if !add_exercise_vis:
                    ListView {
                        for data[i] in exercises:
                        Rectangle {
                            width: 205px;
                            height: 40px;
                            border-width: 5px;
                            padding: 10px;
                            
                            HorizontalBox {
                                alignment: center;

                                Rectangle {
                                    width: remove_exercise_vis ? 160px : 200px;
                                    height: 35px;
                                    border-width: 1.5px;
                                    border-radius: 2px;
                                    border-color: #6b6868;
                                    animate width {
                                         easing: ease-in;
                                         duration: 300ms;
                                    }
                
                                    HorizontalBox {
                                        Text {
                                            text: data.name;
                                            font-size: 16px;
                                        }
            
                                        Switch {
                                            checked: data.activation_status;
                                            toggled => {
                                                exercises[i].activation_status = !exercises[i].activation_status;
                                                changed_activation(exercises[i].name);
                                            }
                                        }
                                    }
                                }
                                
                                if remove_exercise_vis:
                                Rectangle {
                                    width: 30px;
                                    height: 30px;
                                    background: #026F8F;
                                    border-radius: 2px;

                                    Text {
                                        text: "-";
                                    }

                                    TouchArea {
                                        clicked => {
                                            remove_exercise(exercises[i].name);
                                        }
                                    }
                                }
                            }
                        }
                    }

                    if add_exercise_vis :
                    VerticalBox {
                        height: add_exercise_vis ? 0px : parent.height;
                        alignment: center;
                        HorizontalBox {
                            alignment: center;
                            Rectangle {
                                background: #4b4949;
                                width: 300px;
                                height: 200px;
                                
                                VerticalBox {
                                    spacing: 0px;
                                    alignment: center;

                                    HorizontalBox {
                                        alignment: center;

                                        add_exercise_name := TextInput {
                                            color: Colors.white;
                                            font-size: 20px;
                                            text: "Name";
                                            input-type: text;
                                            horizontal-alignment: center;
                                            vertical-alignment: center;

                                            accepted => {
                                                add_exercise(add_exercise_name.text, combo.current-value);
                                                add_exercise_vis = !add_exercise_vis;
                                            }
                                        }
                                    }

                                    HorizontalBox {
                                        alignment: center;

                                        combo := ComboBox {
                                            height: 35px;
                                            width: 80px;
                                            model: ["Reps", "Time"];
                                            current-value: "Reps";
                                            current-index: 0;
                                        }
                                    }

                                    HorizontalBox {
                                        alignment: center;

                                        Rectangle {
                                            width: 80px;
                                            height: 40px;
                                            background: #026F8F;
                                            border-radius: 10px;
                                            border-width: 1px;
                                            border-color: Colors.black;
                                
                                            Text {
                                                text: "Save";
                                                font-size: 20px;
                                            }
                            
                                            TouchArea {
                                                clicked => {
                                                    add_exercise(add_exercise_name.text, combo.current-value);
                                                    add_exercise_vis = !add_exercise_vis;
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                    
                }
            }
            Tab {
                title: "Profiles";
                Rectangle {
                    ListView {
                        for data[i] in profile_names:
                        Rectangle {
                            width: 205px;
                            height: 40px;
                            border-width: 5px;
                            padding: 10px;
                            
                            HorizontalBox {
                                alignment: center;

                                Rectangle {
                                    width: remove_exercise_vis ? 160px : 200px;
                                    height: 35px;
                                    border-width: 1.5px;
                                    border-radius: 2px;
                                    border-color: #6b6868;
                                    animate width {
                                         easing: ease-in;
                                         duration: 300ms;
                                    }
                
                                    HorizontalBox {
                                        Text {
                                            text: data;
                                            font-size: 16px;
                                        }
                                    }
                                }
                                
                                if remove_exercise_vis:
                                Rectangle {
                                    width: 30px;
                                    height: 30px;
                                    background: #026F8F;
                                    border-radius: 2px;

                                    Text {
                                        text: "-";
                                    }

                                    TouchArea {
                                        clicked => {
                                            remove_exercise(exercises[i].name);
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}