export component SettingsButton {
    callback open_settings();

    Rectangle {
        border-radius: 10px;
        width: 50px;
        height: 50px;
        x: -595px;
        y: -395px;
        border-width: 2px;
        border-color: Colors.black;
        
        Image {
            width: parent.width;
            height: parent.height;
            source: @image-url("resources/icon_menu.png");
        }

        TouchArea {
            clicked => {
                open_settings();
            }
        }
    }
}
