export global Theme {
    out property <color> background_color: #111827;
    out property <color> container1: #263243;
    out property <color> container2: #1F2937;
    out property <color> accent: #10B981;
    out property <color> font_color_light: #c9c9c9;
    out property <color> font_color_dark: #727171;
    out property <color> border_color: #414d5f;
    out property <color> negative_accent: #d86f3a;
}