component StartButton inherits Rectangle {
    in-out property <string> text;
    in-out property <bool> status;
    in-out property<int> counter: 0;
    height: 300px;
    width: self.height;
    background: #026F8F;
    border-radius: self.height/2;
    
    Text {
        text: text + " (" + counter + ")";
        font-size: 40px;
    }

    TouchArea {
        enabled: status;
        clicked => { parent.counter += 1; }
    }
}

export component MainWindow inherits Window {
    width: 1200px;
    height: 800px;
    HorizontalLayout {
        alignment: center;
        VerticalLayout {
            alignment: center;
            HorizontalLayout {
                alignment: center;
                StartButton {
                    text: "Start";
                    status: true;
                }
            }
            HorizontalLayout {
                alignment: center;
                Rectangle {
                    width: 200px;
                    height: 40px;
                    background: #41667188;
                    border-radius: 10px;
                    
                    TextInput {
                        color: #FFFFFF;
                        font-size: 20px;
                        selection-background-color: #026F8F;
                        text: "a";
                    }
                }
                Rectangle {
                    width: 200px;
                    height: 40px;
                    background: #41667188;
                    border-radius: 10px;
                    
                    TextInput {
                        color: #FFFFFF;
                        font-size: 20px;
                        selection-background-color: #026F8F;
                        text: "a";
                    }
                }            
            }
        }
    }
}