import { TabWidget, VerticalBox, HorizontalBox, Switch, ListView, Button, TextEdit, ComboBox } from "std-widgets.slint";

enum CurrentView {
    BasicButton,
    RepInput,
    Settings
}

export struct Exercise {
    name: string,
    activation_status: bool,
}

component StartButton inherits Rectangle {
    in-out property <bool> status;
    in-out property <int> time;

    callback button_pressed();

    height: 300px;
    width: self.height;
    background: status ? #026F8F : #B71C1C;
    border-radius: self.height/2;
    border-width: 2px;
    border-color: Colors.black;
    clip: true;
    
    Text {
        text: status ? "Start" : time + "s";
        font-size: 40px;
    }

    TouchArea {
        width: parent.width;
        height: parent.height;
        clicked => { 
            root.button_pressed();
        }
    }
}

component RepInput inherits Rectangle {
    callback save_reps(string);

    in property <string> exercise;

    VerticalLayout {
        alignment: center;
        spacing: 5px;
        HorizontalLayout {
            alignment: center;
            Text {
                text: exercise + "s";
                font-size: 40px;
                color: #026F8F;
            }
        }
        HorizontalLayout {
            alignment: center;
            padding: 10px;
            Text {
                text: "Enter amount of completed reps below";
                font-size: 15px;
            }
        }
        HorizontalLayout {
            alignment: center;
            Rectangle {
                width: 150px;
                height: 40px;
                background: #41667188;
                border-radius: 10px;
                border-width: 1px;
                border-color: Colors.black;
        
                reps := TextInput {
                    color: Colors.white;
                    font-size: 20px;
                    text: "0";
                    input-type: number;
                    horizontal-alignment: center;
                    vertical-alignment: center;
                }
            }
        }
        HorizontalLayout {
            alignment: center;
            Rectangle {
                width: 80px;
                height: 40px;
                background: #026F8F;
                border-radius: 10px;
                border-width: 1px;
                border-color: Colors.black;
    
                Text {
                    text: "Save";
                    font-size: 20px;
                }

                TouchArea {
                    width: parent.width;
                    height: parent.height;
                    clicked => { 
                        root.save_reps(reps.text);
                        reps.text = "0";
                    }
                }
            }
        }
    }
}

component BasicButton {
    callback start_pressed(string, string);

    //Interval Inputs
    in-out property <int> initial_floor_value;
    in-out property <int> initial_ceil_value;

    //Start Button
    in-out property <bool> start_button_status: true;
    in-out property <int> passed_time: 0;

    HorizontalLayout {
        alignment: center;
        VerticalLayout {
            spacing: 20px;
            alignment: center;
            HorizontalLayout {
                alignment: center;
                start_button := StartButton {
                    time: passed_time;
                    status: start_button_status;
                    button_pressed => {
                        root.start_pressed(floor_input.text, ceil_input.text);
                    }
                }
            }
            HorizontalLayout {
                alignment: center;
                spacing: 10px;
                Rectangle {
                    width: 150px;
                    height: 40px;
                    background: #41667188;
                    border-radius: 10px;
                    border-width: 1px;
                    border-color: Colors.black;
                    
                    floor_input := TextInput {
                        color: #FFFFFF;
                        font-size: 20px;
                        input-type: number;
                        text: initial_floor_value;
                        horizontal-alignment: center;
                        vertical-alignment: center;
                    }
                }
                Rectangle {
                    width: 150px;
                    height: 40px;
                    background: #41667188;
                    border-radius: 10px;
                    border-width: 1px;
                    border-color: Colors.black;
                    
                    ceil_input := TextInput {
                        color: #FFFFFF;
                        font-size: 20px;
                        input-type: number;
                        text: initial_ceil_value;
                        horizontal-alignment: center;
                        vertical-alignment: center;
                    }
                }            
            }
        }
    }
}

component SettingsButton {
    callback open_settings();

    Rectangle {
        border-radius: 10px;
        width: 50px;
        height: 50px;
        x: -595px;
        y: -395px;
        border-width: 2px;
        border-color: Colors.black;
        
        Image {
            width: parent.width;
            height: parent.height;
            source: @image-url("resources/icon_menu.png");
        }

        TouchArea {
            clicked => {
                open_settings();
            }
        }
    }
}

component Settings {
    callback changed_general(bool);
    callback changed_activation(string);
    callback add_exercise(string, string);

    in property <bool> setting_general_doubles;
    in-out property <[Exercise]> exercises;
    in-out property <bool> add_exercise_vis: false;
    in-out property <bool> remove_exercise_vis: false;

    width: 600px;
    height: 400px;
    Rectangle {
        border-radius: 2px;
        border-width: 1px;
        border-color: #6b6868;
        TabWidget {
            //Tab {
            //    title: "General";
            //    Rectangle {
            //        VerticalBox {
            //            alignment: start;
            //            //REMINDER statt doppel rectangle vllt vertbox mit spacing
            //            //TODO auf knopfduck schieben sich die Switches zusammen und danach spawn ein knopf
            //            Rectangle {
            //                width: 205px;
            //                height: 40px;
            //                border-width: 5px;
            //                padding: 10px;
            //                
            //                Rectangle {
            //                    width: 200px; 
            //                    height: 35px;
            //                    border-width: 1.5px;
            //                    border-radius: 2px;
            //                    border-color: #6b6868;
            //                    HorizontalBox {
            //                        Text {
            //                            text: "Doubles";
            //                            font-size: 16px;
            //                        }
            //
            //                        doubles := Switch {
            //                            checked: setting_general_doubles;
            //                            toggled => {
            //                                changed_general(doubles.checked);
            //                            }
            //                        }
            //                    }
            //                }
            //            }
            //        }
            //    }
            //}
            Tab {
                title: "Exercises";
                VerticalBox {
                    HorizontalBox {
                        alignment: center;
                        spacing: 15px;
                        Rectangle {
                            height: 30px;
                            width: 30px;
                            background: add_exercise_vis ? #B71C1C : #026F8F;
                            border-radius: 2px;
                            
                            Image {
                                width: parent.width*0.6;
                                height: parent.height*0.6;
                                source: @image-url("resources/icon_plus.png");
                            }

                            TouchArea {
                                enabled: !remove_exercise_vis;
                                clicked => {
                                    add_exercise_vis = !add_exercise_vis;
                                }
                            }
                        }

                        Rectangle {
                            height: 30px;
                            width: 30px;
                            background: remove_exercise_vis ? #B71C1C : #026F8F;
                            border-radius: 2px;

                            Image {
                                width: parent.width*0.6;
                                height: parent.height*0.5;
                                source: @image-url("resources/icon_minus.png");
                            }

                            TouchArea {
                                enabled: !add_exercise_vis;
                                clicked => {
                                    remove_exercise_vis = !remove_exercise_vis;
                                }
                            }
                        }
                    }
                                        
                    if !add_exercise_vis && !remove_exercise_vis :
                    ListView {
                        for data[i] in exercises:
                        Rectangle {
                            width: 205px;
                            height: 40px;
                            border-width: 5px;
                            padding: 10px;
                            
                            Rectangle {
                                width: 200px; 
                                height: 35px;
                                border-width: 1.5px;
                                border-radius: 2px;
                                border-color: #6b6868;
            
                                HorizontalBox {
                                    Text {
                                        text: data.name;
                                        font-size: 16px;
                                    }
        
                                    Switch {
                                        checked: data.activation_status;
                                        toggled => {
                                            exercises[i].activation_status = !exercises[i].activation_status;
                                            changed_activation(exercises[i].name);
                                        }
                                    }
                                }
                            }
                        }
                    }

                    if add_exercise_vis :
                    VerticalBox {
                        height: add_exercise_vis ? 0px : parent.height;
                        alignment: center;
                        HorizontalBox {
                            alignment: center;
                            Rectangle {
                                background: #4b4949;
                                width: 300px;
                                height: 200px;
                                
                                VerticalBox {
                                    spacing: 0px;
                                    alignment: center;

                                    HorizontalBox {
                                        alignment: center;

                                        add_exercise_name := TextInput {
                                            color: Colors.white;
                                            font-size: 20px;
                                            text: "Name";
                                            input-type: text;
                                            horizontal-alignment: center;
                                            vertical-alignment: center;
                                        }
                                    }

                                    HorizontalBox {
                                        alignment: center;

                                        combo := ComboBox {
                                            height: 35px;
                                            width: 80px;
                                            model: ["Reps", "Time"];
                                            current-value: "Reps";
                                            current-index: 0;
                                        }
                                    }

                                    HorizontalBox {
                                        alignment: center;

                                        Rectangle {
                                            width: 80px;
                                            height: 40px;
                                            background: #026F8F;
                                            border-radius: 10px;
                                            border-width: 1px;
                                            border-color: Colors.black;
                                
                                            Text {
                                                text: "Save";
                                                font-size: 20px;
                                            }
                            
                                            TouchArea {
                                                clicked => {
                                                    add_exercise(add_exercise_name.text, combo.current-value);
                                                    add_exercise_vis = !add_exercise_vis;
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                    
                }
            }
            Tab {
                title: "Profiles";
                Rectangle {
    
                }
            }
        }
    }
}

export component MainWindow inherits Window {
    callback start_pressed(string, string);
    callback save_reps(string);
    callback changed_general_settings(bool);
    callback changed_activation_settings(string);
    callback add_exercise(string, string);
    
    //Interval Inputs
    in-out property <bool> floor_input_invalid: false;
    in-out property <int> initial_floor_value;
    in-out property <bool> ceil_input_invalid: false;
    in-out property <int> initial_ceil_value;
    
    //Start Button
    in-out property <bool> start_button_status: true;
    in-out property <int> passed_time: 0;
    
    //Exercise
    in property <string> chosen_exercise: "";

    //View
    in-out property <CurrentView> current_view: CurrentView.BasicButton;

    //Settings
    in-out property <bool> setting_general_doubles: true;
    in-out property <[Exercise]> exercises;


    width: 1200px;
    height: 800px;

    RepInput {
        visible: current_view == CurrentView.RepInput;
        exercise: chosen_exercise;
        save_reps(reps) => {
            root.save_reps(reps);
        }
    }

    BasicButton {
        visible: current_view == CurrentView.BasicButton;
        initial_floor_value: initial_floor_value;
        initial_ceil_value: initial_ceil_value;
        start_button_status: start_button_status;
        passed_time: passed_time;
        start_pressed(floor, ceil) => {
            start_pressed(floor, ceil);
            passed_time = 0;
        }
    }
    
    SettingsButton {
        property <CurrentView> last_view;
        open_settings => {
            if current_view == CurrentView.Settings {
                current_view = last_view;
            } else {
                last_view = current_view;
                current_view = CurrentView.Settings;
            }
        }
    }

    Settings {
        visible: current_view == CurrentView.Settings;
        setting_general_doubles: setting_general_doubles;
        exercises: exercises;
        changed_general(doubles) => {
            changed_general_settings(doubles);
        }
        changed_activation(name) => {
            changed_activation_settings(name);
        }
        add_exercise(name, type) => {
            add_exercise(name, type);
        }
    }
}