import {
    TabWidget,
    ComboBox,
    HorizontalBox,
    VerticalBox,
} from "std-widgets.slint";
import { Theme } from "Theme.slint";

export struct GeneralPart {
    reps: int,
    amount: int,
    max: int,
}
export struct ChronoElement {
    date: string,
    value: int,
}
export struct VisData {
    general: GeneralPart,
    chrono: [ChronoElement],
    highest_value: int}

component Point inherits Rectangle {
    width: 9px;
    height: self.width;
    border-radius: self.width / 2;
    background: Theme.accent;
}

export component Visualisation {
    callback changed_visualisation_exercise(string, string, int);
    callback changed_visualisation_interval(string, string, int);
    in property <[string]> visualisable_exercise_names;
    in property <VisData> visualisation_data;
    in-out property <string> current_exercise: combo.current-value;
    in-out property <string> current_interval: "day";
    in-out property <int> unit_count: 30;
    property <bool> lines_visible: false;
    Rectangle {
        padding: 10px;
        width: 900px;
        height: 580px;
        background: Theme.container1;
        HorizontalBox {
            VerticalBox {
                alignment: center;
                //Übungsauswahl
                combo := ComboBox {
                    width: 200px;
                    height: 35px;
                    x: 10px;
                    //y: 20px;
                    model: visualisable_exercise_names;
                    selected(current-value) => {
                        changed_visualisation_exercise(current_exercise, current_interval, unit_count);
                    }
                }
                //General Daten
                Rectangle {
                    border-radius: 3px;
                    border-color: Theme.accent;
                    border-width: 1px;
                    height: 120px;
                    padding: 10px;
                    VerticalBox {
                        alignment: start;
                        Text {
                            text: "Total: " + visualisation_data.general.reps;
                            font-size: 25px;
                            font-family: "Inter";
                            color: Theme.accent;
                        }

                        Text {
                            text: "Max: " + visualisation_data.general.max;
                            font-size: 25px;
                            font-family: "Inter";
                            color: Theme.accent;
                        }

                        Text {
                            text: "Amount: " + visualisation_data.general.amount;
                            font-size: 25px;
                            font-family: "Inter";
                            color: Theme.accent;
                        }
                    }
                }

                Text {
                    text: "Since: " + visualisation_data.chrono[0].date;
                    font-size: 18px;
                    font-family: "Inter";
                    horizontal-alignment: center;
                    color: Theme.font_color_dark;
                }
                //Einheiten-Anzahl
                Rectangle {
                    height: 40px;
                    HorizontalBox {
                        Rectangle {
                            background: unit_count == 7 ? Theme.accent : Theme.container2;
                            border-radius: 3px;
                            border-width: 1.5px;
                            border-color: Theme.accent;
                            Text {
                                text: "7";
                                color: unit_count == 7 ? Theme.container2 : Theme.font_color_dark;
                            }

                            TouchArea {
                                clicked => {
                                    unit_count = 7;
                                    changed_visualisation_interval(current_exercise, current_interval, 7);
                                }
                            }
                        }

                        Rectangle {
                            background: unit_count == 14 ? Theme.accent : Theme.container2;
                            border-radius: 3px;
                            border-width: 1.5px;
                            border-color: Theme.accent;
                            Text {
                                text: "14";
                                color: unit_count == 14 ? Theme.container2 : Theme.font_color_dark;
                            }

                            TouchArea {
                                clicked => {
                                    unit_count = 14;
                                    changed_visualisation_interval(current_exercise, current_interval, 14);
                                }
                            }
                        }

                        Rectangle {
                            background: unit_count == 30 ? Theme.accent : Theme.container2;
                            border-radius: 3px;
                            border-width: 1.5px;
                            border-color: Theme.accent;
                            Text {
                                text: "30";
                                color: unit_count == 30 ? Theme.container2 : Theme.font_color_dark;
                            }

                            TouchArea {
                                clicked => {
                                    unit_count = 30;
                                    changed_visualisation_interval(current_exercise, current_interval, 30);
                                }
                            }
                        }

                        Rectangle {
                            background: unit_count == 90 ? Theme.accent : Theme.container2;
                            border-radius: 3px;
                            border-width: 1.5px;
                            border-color: Theme.accent;
                            Text {
                                text: "90";
                                color: unit_count == 90 ? Theme.container2 : Theme.font_color_dark;
                            }

                            TouchArea {
                                clicked => {
                                    unit_count = 90;
                                    changed_visualisation_interval(current_exercise, current_interval, 90);
                                }
                            }
                        }

                        Rectangle {
                            background: unit_count == 365 ? Theme.accent : Theme.container2;
                            border-radius: 3px;
                            border-width: 1.5px;
                            border-color: Theme.accent;
                            Text {
                                text: "365";
                                color: unit_count == 365 ? Theme.container2 : Theme.font_color_dark;
                            }

                            TouchArea {
                                clicked => {
                                    unit_count = 365;
                                    changed_visualisation_interval(current_exercise, current_interval, 365);
                                }
                            }
                        }
                    }
                }
            }

            VerticalBox {
                //Zeitintervalle
                Rectangle {
                    height: 50px;
                    HorizontalBox {
                        Rectangle {
                            background: current_interval == "day" ? Theme.accent : Theme.container2;
                            border-radius: 3px;
                            border-width: 1.5px;
                            border-color: Theme.accent;
                            Text {
                                text: "Day";
                                color: current_interval == "day" ? Theme.container2 : Theme.font_color_dark;
                            }

                            TouchArea {
                                clicked => {
                                    current_interval = "day";
                                    changed_visualisation_interval(current_exercise, "day", unit_count);
                                }
                            }
                        }

                        Rectangle {
                            background: current_interval == "week" ? Theme.accent : Theme.container2;
                            border-radius: 3px;
                            border-width: 1.5px;
                            border-color: Theme.accent;
                            Text {
                                text: "Week";
                                color: current_interval == "week" ? Theme.container2 : Theme.font_color_dark;
                            }

                            TouchArea {
                                clicked => {
                                    current_interval = "week";
                                    changed_visualisation_interval(current_exercise, "week", unit_count);
                                }
                            }
                        }

                        Rectangle {
                            background: current_interval == "month" ? Theme.accent : Theme.container2;
                            border-radius: 3px;
                            border-width: 1.5px;
                            border-color: Theme.accent;
                            Text {
                                text: "Month";
                                color: current_interval == "month" ? Theme.container2 : Theme.font_color_dark;
                            }

                            TouchArea {
                                clicked => {
                                    current_interval = "month";
                                    changed_visualisation_interval(current_exercise, "month", unit_count);
                                }
                            }
                        }

                        Rectangle {
                            background: current_interval == "year" ? Theme.accent : Theme.container2;
                            border-radius: 3px;
                            border-width: 1.5px;
                            border-color: Theme.accent;
                            Text {
                                text: "Year";
                                color: current_interval == "year" ? Theme.container2 : Theme.font_color_dark;
                            }

                            TouchArea {
                                clicked => {
                                    current_interval = "year";
                                    changed_visualisation_interval(current_exercise, "year", unit_count);
                                }
                            }
                        }

                        Rectangle {
                            background: Theme.container2;
                            border-radius: 3px;
                            border-width: 1.5px;
                            border-color: Theme.accent;
                            Text {
                                text: "Lines";
                            }

                            TouchArea {
                                clicked => {
                                    lines_visible = !lines_visible;
                                }
                            }
                        }
                    }
                }
                //Graph
                Rectangle {
                    property <length> ylimit: 430px;
                    property <int> ylimitint: 430;
                    //y-axis
                    Rectangle {
                        background: Theme.container1;
                        x: 10px;
                        width: 3px;
                        height: 465px;
                    }                    
                    //bar1
                    Rectangle {
                        background: Theme.container1;
                        x: 10px;
                        width: 20px;
                        height: 3px;
                        y: 460px - (1 / 1) * ylimit;
                        Text {
                            text: visualisation_data.highest-value;
                            x: 5px;
                            y: -15px;
                            color: Theme.font_color_dark;
                            font-family: "Inter";
                            font-size: 14px;
                        }
                    }

                    Rectangle {
                        background: Theme.container1;
                        x: 10px;
                        width: parent.width - 20px;
                        height: 1px;
                        y: 460px - (1 / 1) * ylimit + 1.5px;
                    }
                    //bar0.75
                    Rectangle {
                        background: Theme.container1;
                        x: 10px;
                        width: 20px;
                        height: 3px;
                        y: 460px - (0.75 / 1) * ylimit;
                        Text {
                            text: visualisation_data.highest-value * 0.75;
                            x: 5px;
                            y: -15px;
                            color: Theme.font_color_dark;
                            font-family: "Inter";
                            font-size: 14px;
                        }
                    }

                    Rectangle {
                        background: Theme.container1;
                        x: 10px;
                        width: parent.width - 20px;
                        height: 1px;
                        y: 460px - (0.75 / 1) * ylimit + 1px;
                    }
                    //bar0.5
                    Rectangle {
                        background: Theme.container1;
                        x: 10px;
                        width: 20px;
                        height: 3px;
                        y: 460px - (0.5 / 1) * ylimit;
                        Text {
                            text: visualisation_data.highest-value * 0.5;
                            x: 5px;
                            y: -15px;
                            color: Theme.font_color_dark;
                            font-family: "Inter";
                            font-size: 14px;
                        }
                    }

                    Rectangle {
                        background: Theme.container1;
                        x: 10px;
                        width: parent.width - 20px;
                        height: 1px;
                        y: 460px - (0.5 / 1) * ylimit + 1.5px;
                    }
                    //bar0.25
                    Rectangle {
                        background: Theme.container1;
                        x: 10px;
                        width: 20px;
                        height: 3px;
                        y: 460px - (0.25 / 1) * ylimit;
                        Text {
                            text: visualisation_data.highest-value * 0.25;
                            x: 5px;
                            y: -15px;
                            color: Theme.font_color_dark;
                            font-family: "Inter";
                            font-size: 14px;
                        }
                    }

                    Rectangle {
                        background: Theme.container1;
                        x: 10px;
                        width: parent.width - 20px;
                        height: 1px;
                        y: 460px - (0.25 / 1) * ylimit + 1px;
                    }
                    //bar0
                    Rectangle {
                        background: Theme.container1;
                        x: 10px;
                        width: 20px;
                        height: 3px;
                        y: 460px;
                        Text {
                            text: 0;
                            x: 5px;
                            y: -15px;
                            color: Theme.font_color_dark;
                            font-family: "Inter";
                            font-size: 14px;
                        }
                    }

                    Rectangle {
                        background: Theme.container1;
                        x: 10px;
                        width: parent.width - 20px;
                        height: 1px;
                        y: 460px + 1.5px;
                    }

                    background: Theme.container2;
                    for data_point[i] in visualisation_data.chrono: point := Point {
                        x: 20px + (52 / visualisation_data.chrono.length * i) * 12px;
                        y: 460px - (data_point.value / visualisation_data.highest-value) * ylimit - point.height / 2 + 1.5px;
                        touch := TouchArea { }

                        Rectangle {
                            background: Theme.container1;
                            width: 80px;
                            height: 35px;
                            x: -point.width - 60px;
                            y: -point.height - (self.height - 2px);
                            visible: touch.has-hover;
                            border-radius: 3px;
                            border-color: Theme.accent;
                            border-width: 1px;
                            z: -1;
                            Text {
                                text: data-point.value;
                                font-size: 18px;
                                font-family: "Inter";
                                y: 2px;
                            }

                            Text {
                                text: touch.has-hover ? data-point.date : "";
                                color: touch.has-hover ? Theme.font_color_dark : Theme.container2;
                                font-size: 12px;
                                font-family: "Inter";
                                y: 20px;
                            }
                        }

                        property <float> x_end: (52.0 / visualisation_data.chrono.length) * 12;
                        property <int> y_end: ((460 - (visualisation_data.chrono[i + 1].value / visualisation_data.highest-value) * ylimitint + 1.5) - (460 - (visualisation_data.chrono[i].value / visualisation_data.highest-value) * ylimitint + 1.5));
                        if (y_end >= 0 && i != (visualisation_data.chrono.length - 1)): Path {
                            visible: lines_visible;
                            width: (52.0 / visualisation_data.chrono.length) * 12px + 8px;
                            height: ((460 - (visualisation_data.chrono[i + 1].value / visualisation_data.highest-value) * ylimitint + 1.5) - (460 - (visualisation_data.chrono[i].value / visualisation_data.highest-value) * ylimitint + 1.5)) * 1px + 3px;
                            x: 1.5px;
                            y: 3px;
                            fill: transparent;
                            stroke: Theme.accent;
                            stroke-width: 2px;
                            MoveTo {
                                x: 0;
                                y: 0;
                            }

                            LineTo {
                                x: x_end;
                                y: y_end;
                            }
                        }
                        if (y_end < 0): Path {
                            visible: lines_visible;
                            width: (52.0 / visualisation_data.chrono.length) * 12px + 8px;
                            height: abs(((460 - (visualisation_data.chrono[i + 1].value / visualisation_data.highest-value) * ylimitint + 1.5) - (460 - (visualisation_data.chrono[i].value / visualisation_data.highest-value) * ylimitint + 1.5)) * 1px) + 3px;
                            x: 1.5px;
                            y: (((460 - (visualisation_data.chrono[i + 1].value / visualisation_data.highest-value) * ylimitint + 1.5) - (460 - (visualisation_data.chrono[i].value / visualisation_data.highest-value) * ylimitint + 1.5)) * 1px);
                            fill: transparent;
                            stroke: Theme.accent;
                            stroke-width: 2px;
                            MoveTo {
                                x: 0;
                                y: 0;
                            }

                            LineTo {
                                x: x_end;
                                y: y_end;
                            }
                        }
                    }
                }
            }
        }
    }
}
