import { TabWidget, ComboBox, HorizontalBox, VerticalBox } from "std-widgets.slint";
import { Theme } from "Theme.slint";

export struct GeneralPart {
    reps: int,
    amount: int,
    max: int,
}
export struct ChronoElement {
    date: string,
    value: int,
}
export struct VisData {
    general: GeneralPart,
    chrono: [ChronoElement],
    highest_value: int
}

component Point inherits Rectangle{
    width: 9px;
    height: self.width;
    border-radius: self.width/2;
    background: Theme.accent;
}

export component Visualisation {
    callback changed_visualisation_exercise(string);
    callback changed_visualisation_interval(string, string);

    in property <[string]> visualisable_exercise_names;
    in property <VisData> visualisation_data;
    in-out property <string> current_exercise: combo.current-value;

    Rectangle {
        padding: 10px;
        width: 900px;
        height: 580px;
        background: Theme.container1;

        HorizontalBox {
            VerticalBox {
                alignment: center;
                //Übungsauswahl
                combo := ComboBox {
                    width: 200px;
                    height: 35px;
                    x: 10px;
                    //y: 20px;
                    model: visualisable_exercise_names;
                    selected(current-value) => {
                        changed_visualisation_exercise(current_exercise);
                    }
                }
                //General Daten
                Rectangle {
                    border-radius: 3px;
                    border-color: Theme.accent;
                    border-width: 1px;
                    height: 120px;
                    padding: 10px;
                    VerticalBox {
                        alignment: start;
                        Text {
                            text: "Total: " + visualisation_data.general.reps;
                            font-size: 25px;
                            font-family: "Inter";
                            color: Theme.accent;
                        }
                        Text {
                            text: "Max: " + visualisation_data.general.max;
                            font-size: 25px;
                            font-family: "Inter";
                            color: Theme.accent;
                            
                        }
                        Text {
                            text: "Amount: " + visualisation_data.general.amount;
                            font-size: 25px;
                            font-family: "Inter";
                            color: Theme.accent;

                        }
                    }
                }
            }
            VerticalBox {
                //Zeitintervalle
                Rectangle {
                    height: 50px;
                    HorizontalBox {
                        Rectangle {
                            background: Theme.container2;
                            border-radius: 3px;
                            border-width: 1.5px;
                            border-color: Theme.accent;
                            Text {
                                text: "Day";
                            }
                            TouchArea {
                                clicked => {changed_visualisation_interval(current_exercise, "day");}
                            }
                        }
                        Rectangle {
                            background: Theme.container2;
                            border-radius: 3px;
                            border-width: 1.5px;
                            border-color: Theme.accent;

                            Text {
                                text: "Week";
                            }

                            TouchArea {
                                clicked => {changed_visualisation_interval(current_exercise, "week");}
                            }
                        }
                        Rectangle {
                            background: Theme.container2;
                            border-radius: 3px;
                            border-width: 1.5px;
                            border-color: Theme.accent;
                            Text {
                                text: "Month";
                            }

                            TouchArea {
                                clicked => {changed_visualisation_interval(current_exercise, "month");}
                            }
                        }
                        Rectangle {
                            background: Theme.container2;
                            border-radius: 3px;
                            border-width: 1.5px;
                            border-color: Theme.accent;
                            Text {
                                text: "Year";
                            }

                            TouchArea {
                                clicked => {changed_visualisation_interval(current_exercise, "year");}
                            }
                        }
                    }
                }
                //Graph
                Rectangle {
                    Rectangle {
                        background: Theme.container1;
                        x: 10px;
                        width: 3px;
                        height: 465px;
                    }
                    Rectangle {
                        background: Theme.container1;
                        x: 10px;
                        y: 477.5px;
                        width: parent.width - 20px;
                        height: 3px;
                    }
                    background: Theme.container2;
                    for data_point[i] in visualisation_data.chrono: point := Point {
                        x: 20px + (52/visualisation_data.chrono.length * i) * 12px;
                        y: 450px - (data_point.value/visualisation_data.highest-value) * 350px;
                        touch := TouchArea {}
                        Rectangle {
                            background: Theme.container1;
                            width: 60px;
                            height: 30px;
                            x: -point.width - 60px;
                            y: -point.height - (self.height - 2px); 
                            visible: touch.has-hover;
                            border-radius: 3px;
                            border-color: Theme.accent;
                            border-width: 1px;
                            z: -1;
                            Text {
                                text: data-point.value;
                                font-size: 18px;
                                font-family: "Inter";
                            }
                        }
                    }
                }
            }
        }
    }
}

//TODO ordentlich angeordnet
//TODO Skalen
//TODO kleiner Text seit wann die Daten gewonnen gesammelt wurden
//maybe linien