import { Theme } from "Theme.slint";
 
export component VisualisationButton {
    callback open_visualisation();

    Rectangle {
        border-radius: 10px;
        width: 50px;
        height: 50px;
        x: 540px;
        y: -395px;
        
        Image {
            width: parent.width;
            height: parent.height;
            colorize: touch.has-hover ? Theme.accent_hovered : Theme.accent;
            source: @image-url("resources/icon_graph.png");
        }

        touch := TouchArea {
            clicked => {
                open_visualisation();
            }
        }
    }
}
